apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-backend
  template:
    metadata:
      labels:
        app: myapp-backend
    spec:
      containers:
        - name: myapp-backend
          image: 486408064722.dkr.ecr.us-east-1.amazonaws.com/frontend-backend-application:backend-latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-backend-service
spec:
  selector:
    app: myapp-backend
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
